version: "2.4"
services:
  cassandra:
    image: cassandra:3.11
    environment:
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_LISTEN_ADDRESS=127.0.0.1
    mem_limit: 1G
    memswap_limit: -1
    # Uncomment for benchmarks to avoid re-ingesting for each run
    # volumes:
      # - /data/cassandra:/var/lib/cassandra
